//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssFeedReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class RssFeed
    {
        public int FeedID { get; set; }
        public string FeedUrl { get; set; }
        public System.DateTime FeedPublishDate { get; set; }
        public bool FeedRead { get; set; }
    }
}
